@startuml

node neo4j-store {
    [client]
    [schema-model]
    [schema]
    [dsl-model]
    [dsl]
    [dsl-model-annotation]
    [dsl-annotation-processor]
}

node exmaples {
    [cypher-client]
    [store-client]
    [dsl-ksp-client]
    [dsl-client]
}

[client] <-- [cypher-client] : uses

[schema] <-- [store-client] : uses
[schema-model] <-- [store-client] : uses

[dsl] <-- [dsl-client] : uses
[dsl-model] <-- [dsl-client] : uses

[dsl-model-annotation] <-- [dsl-ksp-client] : uses
[dsl-annotation-processor] <.. [dsl-ksp-client] : uses
[dsl] <.. [dsl-ksp-client] : uses
[dsl-model] <.. [dsl-ksp-client] : uses

@enduml