@startuml

[common] <.. [client] : uses

[common] <.. [schema] : uses

[error] <.. [schema] : uses

[model] <.. [schema] : uses

[client] <.. [schema] : uses

[schema] <.. [dsl] : uses

[common] <... [transaction] : uses


@enduml