name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Setup jdk16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
          architecture: x64
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew --no-daemon build -info --stacktrace
